# -*- coding: utf-8 -*-
"""God_Mod_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TOpt5iJ0_hC9IoaF3lk-j0ovoHGNAWJQ
"""

"Crear lista para números primos"
Lista_primos = []

"Definición de la función primo"
def is_prime(y):
  for x in range(2,y):
    if y%x == 0:
      result = False
      break
  if y == x + 1:
      result = True 
  return result
is_prime(5)

"funcion primos"
contador = 0
last_prime = 1
next_number = last_prime + 1
print (2)

while contador<74:
  next_number = next_number + 1

  if is_prime (next_number):

    contador = contador + 1
    last_prime = next_number
    print (last_prime)

"Crear lista de primos primos"
Lista_primos.append(last_prime)

from numpy import linspace
from pandas import DataFrame 
import pandas as pd

Conjetura = pd.DataFrame()
Conjetura["Primos"] = Lista_primos
print (Conjetura)

"Producto de sus dígitos"

from pandas import DataFrame 
import pandas as pd
Lista_producto = []
producto = 1
for numero in Lista_primos:
  while numero != 0:
    digito = numero % 10
    producto = producto*digito
    numero //= 10
  Lista_producto.append(producto)
  producto = 1

Conjetura['Producto']= Lista_producto
print (Conjetura)

"Obtener el espejo del número primo"
import pandas as pd

lista_espejo = []
reverso = 0
for n in Lista_primos:
  while n!=0:
    cifra = n%10
    reverso = reverso *10 + cifra
    n = n//10
  lista_espejo.append(reverso)
  reverso = 0

Conjetura["Espejo"] = lista_espejo

print(Conjetura)